name: shoppingApi
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project code
        uses: actions/checkout@v4
      - name: Set up Node js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Start JSON server
        run: npx json-server db.json --port 3000 &
      - name: Wait for server to start
        run: sleep 3
      - name: Install Postman CLI
        run: curl -s https://dl-cli.pstmn.io/install/linux64.sh | sh
      - name: Login to Postman
        run: postman login --with-api-key ${{ secrets.shoppingApi_KEY }}
      - name: Run shoppingApi
        run: |
          postman collection run "54348994-6e318fe9-2492-48bc-b664-f2a3dd34ba86" 
            -e "54348994-97c74c8f-ea10-4b8f-a4ad-5d991f38b9c3"